export const COLORS = [
    { name: 'Black', value: 0x0000 },
    { name: 'Navy', value: '0x000F' },
    { name: 'Dark Green', value: '0x03E0' },
    { name: 'Dark Cyan', value: '0x03EF' },
    { name: 'Maroon', value: '0x7800' },
    { name: 'Purple', value: '0x780F' },
    { name: 'Olive', value: '0x7BE0' },
    { name: 'Light Grey', value: '0xC618' },
    { name: 'Dark Grey', value: '0x7BEF' },
    { name: 'Blue', value: '0x001F' },
    { name: 'Green', value: '0x07E0' },
    { name: 'Cyan', value: '0x07FF' },
    { name: 'Red', value: '0xF800' },
    { name: 'Magenta', value: '0xF81F' },
    { name: 'Yellow', value: '0xFFE0' },
    { name: 'White', value: '0xFFFF' },
    { name: 'Orange', value: '0xFD20' },
    { name: 'Green Yellow', value: '0xAFE5' },
    { name: 'Pink', value: '0xFC18' }
  ];
